spring:
  profiles:
    include: swagger
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz947v41a829fdmr2go.mysql.rds.aliyuncs.com:3306/skm-manage?&allowMultiQueries=true&createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: skm_manage
    password: skm_manage@123

server:
  port: 9000