spring:
  profiles:
    include: swagger
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz947v41a829fdmr2go.mysql.rds.aliyuncs.com:3306/exa-test?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: exa
    password: exa@123456
server:
  port: 9000