spring:
  application:
    name: exa
  profiles:
    active: @env@
  session:
    store-type: redis
  jackson:
    deserialization:
      fail_on_unknown_properties: false
server:
  port: 8080
  servlet:
    session:
      timeout: 3M  # 默认3分钟的有效期，登录成功后再设置对应的session为30天
mybatis:
  mapper-locations: classpath*:mappers/**/*.xml
  configuration:
    lazy-loading-enabled: true
    map-underscore-to-camel-case: true
logging:
  file: logs/${spring.application.name}.log
  level:
    com.skm.exa.mybatis: DEBUG
    com.skm.exa.persistence.dao: DEBUG
